import { fromKeys } from 'reax'

export default fromKeys([
  'PRODUCTS_LOADING',
  'PRODUCTS_CATEGORIES_LOADED',
  'PRODUCTS_PRODUCTS_LOADED',
  'PRODUCTS_UPDATE_FILTER',
  'PRODUCTS_RESET',
  'PRODUCTS_CATEGORIES_RESET',
  'PRODUCTS_PAGE_TO',
  'PRODUCTS_UPDATE_CANVAS_SIZE',
  'PRODUCTS_CLICK_MODEL',
  'PRODUCTS_CHANGE_SCALE',
])
